apiVersion: v1
kind: Service
metadata:
  name: wemo-db
spec:
  ports:
    - port: 5432
  selector:
    app: wemo-db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wemo-db
spec:
  serviceName: "wemo-db"
  replicas: 1
  selector:
    matchLabels:
      app: wemo-db
  template:
    metadata:
      labels:
        app: wemo-db
    spec:
      containers:
        - name: wemo-db
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
